# dein本体
    [[plugins]]
    repo = 'Shougo/dein.vim'

    [[plugins]]
    repo = 'Shougo/vimproc.vim'
    build = 'make'

#vim-surround
    [[plugins]]
    repo = 'tpope/vim-surround'

#NERDtree
    [[plugins]]
    repo = 'scrooloose/nerdtree'

#neosnippet-snippets
    [[plugins]]
    repo = 'Shougo/neosnippet-snippets'

#autosave
    [[plugins]]
    repo = 'vim-scripts/vim-auto-save'

#lexima
    [[plugins]]
    repo = 'cohama/lexima.vim'
